"""add repr

Revision ID: 01323ffa5f93
Revises: a00f7ff5b547
Create Date: 2024-04-02 15:45:10.876336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01323ffa5f93'
down_revision = 'a00f7ff5b547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
